Add opportunity to cancel notification

diff --git a/commands/slownotify b/commands/slownotify
--- a/commands/slownotify
+++ b/commands/slownotify
@@ -5,9 +5,11 @@ function slownotify() {
 
     # Default timeout (in seconds)
     DEFAULT_TIMEOUT=5
+    DEFAULT_CANCEL_DELAY=10
 
     # Parse command line arguments
     timeout=$DEFAULT_TIMEOUT  # Set default timeout
+    cancel_delay=$DEFAULT_CANCEL_DELAY
     custom_message=false
     cmd=()  # Initialize command array
 
@@ -16,6 +18,15 @@ function slownotify() {
         -t)
         if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
             timeout=$2
+            shift 2
+        else
+            echo "Error: Argument for $1 is missing" >&2
+            exit 1
+        fi
+        ;;
+        -c)
+        if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
+            cancel_delay=$2
             shift 2
         else
             echo "Error: Argument for $1 is missing" >&2
@@ -52,7 +63,7 @@ function slownotify() {
 
     # Check if any command is specified
     if [ ${#cmd[@]} -eq 0 ]; then
-    echo "Usage: $(basename $0) [ -t <timeout in seconds> ] [ -m <custom message> ] <command>"
+    echo "Usage: $(basename $0) [ -t <timeout in seconds> ] [ -c <cancel delay in seconds> ] [ -m <custom message> ] <command>"
     exit 1
     fi
 
@@ -71,10 +82,13 @@ function slownotify() {
     # Check if duration exceeded the timeout using bc
     if [ $(echo "$duration >= $timeout" | bc) -eq 1 ]; then
 
-       # Set default message if no custom message is provided
+        # Set default message if no custom message is provided
         if [ "$custom_message" != "true" ]; then
             message="command finished with status ${return_status} after ${duration}s: ${cmd[*]}"
         fi
+
+        echo "Notifying in ${cancel_delay}s (Ctrl-C to cancel)..."
+        sleep "$cancel_delay"
 
         echo "$message"
         notify "$message"
